org.gradle.jvmargs=-Xmx3G -Dhttp.agent="Gradle/8.8" -Dsun.net.client.defaultConnectTimeout=10000 -Dsun.net.client.defaultReadTimeout=10000
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=1.20.1-47.3.0
forge_version_range=[47,)
loader_version_range=[47,)

mod_id=beeworks
mod_name=Bee Works
mod_license=MIT
mod_version=1.0.1
mod_group_id=com.qefwgrhgj.beeworks
mod_authors=Guardian, DSCHEL
mod_description=Standalone wooden beehives and bee AI fixes without Blueprint dependency.
