org.gradle.jvmargs=-Xmx3G -Dhttp.agent="Gradle/8.8" -Dsun.net.client.defaultConnectTimeout=10000 -Dsun.net.client.defaultReadTimeout=10000
org.gradle.daemon=false
org.gradle.parallel=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[1,)

mod_id=beeworks
mod_name=Bee Works
mod_license=MIT
mod_version=1.0.0
mod_group_id=com.qefwgrhgj.beeworks
mod_authors=Guardian, DSCHEL
mod_description=Standalone wooden beehives and bee AI fixes for Minecraft 1.21.1 NeoForge without Blueprint dependency.
